"""Model Fine-Tuning Infrastructure (M20)

This script uses Unsloth and HuggingFace TRL to fine-tune a Llama-3-8B model
on the 'dataset/training_data.jsonl' generated by the Dhrubo DatasetGeneratorAgent.

Prerequisites:
    pip install "unsloth[colab-new] @ git+https://github.com/unslothai/unsloth.git"
    pip install --no-deps "xformers<0.0.27" "trl<0.9.0" peft accelerate bitsandbytes
"""

from pathlib import Path

from datasets import load_dataset
from transformers import TrainingArguments
from trl import SFTTrainer

try:
    from unsloth import FastLanguageModel, is_bfloat16_supported
except ImportError:
    print("Unsloth not installed. Please install it to run fine-tuning.")
    print("pip install unsloth")
    # Exit gracefully if imported without dependencies
    import sys
    sys.exit(0)

# Configuration
DATASET_PATHS = ["dataset/training_data.jsonl", "dataset/real_training_data.jsonl"]
MODEL_NAME = "unsloth/llama-3-8b-Instruct-bnb-4bit"
OUTPUT_DIR = "outputs/dhrubo_slm_v1"
MAX_SEQ_LENGTH = 8192 # Support long DOM contexts

def main():
    existing_paths = [p for p in DATASET_PATHS if Path(p).exists()]
    if not existing_paths:
        print(f"No datasets found from {DATASET_PATHS}. Please run the audit pipeline or download script first.")
        return

    print("Loading model...")
    model, tokenizer = FastLanguageModel.from_pretrained(
        model_name=MODEL_NAME,
        max_seq_length=MAX_SEQ_LENGTH,
        dtype=None,
        load_in_4bit=True,
    )

    # Configure LoRA Adapters
    model = FastLanguageModel.get_peft_model(
        model,
        r=16,
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj",
                        "gate_proj", "up_proj", "down_proj"],
        lora_alpha=16,
        lora_dropout=0,
        bias="none",
        use_gradient_checkpointing="unsloth",
        random_state=3407,
        use_rslora=False,
        loftq_config=None,
    )

    print("Loading dataset...")
    # Map standard OpenAI {"messages": [...]} to the format TRL expects
    def format_chat_template(examples):
        texts = []
        for messages in examples["messages"]:
            text = tokenizer.apply_chat_template(messages, tokenize=False, add_generation_prompt=False)
            texts.append(text)
        return {"text": texts}

    dataset = load_dataset("json", data_files=existing_paths, split="train")
    dataset = dataset.map(format_chat_template, batched=True)

    print(f"Loaded {len(dataset)} training examples. Initializing Trainer...")

    trainer = SFTTrainer(
        model=model,
        tokenizer=tokenizer,
        train_dataset=dataset,
        dataset_text_field="text",
        max_seq_length=MAX_SEQ_LENGTH,
        dataset_num_proc=2,
        packing=False,
        args=TrainingArguments(
            per_device_train_batch_size=2,
            gradient_accumulation_steps=4,
            warmup_steps=5,
            num_train_epochs=3,
            learning_rate=2e-4,
            fp16=not is_bfloat16_supported(),
            bf16=is_bfloat16_supported(),
            logging_steps=1,
            optim="adamw_8bit",
            weight_decay=0.01,
            lr_scheduler_type="linear",
            seed=3407,
            output_dir=OUTPUT_DIR,
        ),
    )

    print("Starting Training...")
    trainer_stats = trainer.train()

    print("Training complete! Saving LoRA adapters...")
    model.save_pretrained(f"{OUTPUT_DIR}/lora_model")
    tokenizer.save_pretrained(f"{OUTPUT_DIR}/lora_model")

    # Optional: Save to GGUF for Ollama/llama.cpp
    print("Exporting to GGUF (Q4_K_M)...")
    try:
        model.save_pretrained_gguf(f"{OUTPUT_DIR}/dhrubo-v1", tokenizer, quantization_method="q4_k_m")
        print(f"Successfully exported to {OUTPUT_DIR}/dhrubo-v1-unsloth.Q4_K_M.gguf")
    except Exception as e:
        print(f"Failed to export GGUF: {e}")

if __name__ == "__main__":
    main()
