"""Deterministic LLM provider used in tests and offline runs."""

from __future__ import annotations

import json
import re
from typing import Any

from dhrubo.llm.interface import ILLMProvider, LLMCompletion, LLMRequest

_FALLBACK_SEO = {
    "score": 75,
    "summary": "Mock SEO audit — set OPENAI_API_KEY for real analysis.",
    "issues": [
        {
            "severity": "info",
            "title": "Mock response",
            "detail": "This audit was generated by the offline mock provider.",
            "recommendation": "Set OPENAI_API_KEY to enable real reviewer analysis.",
        }
    ],
}


_FALLBACK_UI = {
    "score": 70,
    "summary": "Mock UI audit — set OPENAI_API_KEY for real visual analysis.",
    "issues": [
        {
            "severity": "info",
            "title": "Mock response",
            "detail": "This UI review was generated by the offline mock provider.",
            "recommendation": "Set OPENAI_API_KEY to enable real vision-based UI review.",
        }
    ],
    "viewports_seen": [],
}


_FALLBACK_PERF = {
    "score": 65,
    "summary": "Mock performance audit — set OPENAI_API_KEY + PAGESPEED_API_KEY for real analysis.",
    "issues": [
        {
            "severity": "info",
            "title": "Mock response",
            "detail": "This performance review was generated by the offline mock provider.",
            "recommendation": "Set PAGESPEED_API_KEY (or GOOGLE_API_KEY) and OPENAI_API_KEY to enable real PageSpeed-Insights-based performance review.",
        }
    ],
    "metrics": [
        {
            "id": "largest-contentful-paint",
            "title": "Largest Contentful Paint",
            "value": 2500.0,
            "display_value": "2.5 s",
            "score": 0.5,
        }
    ],
    "opportunities": [],
    "has_field_data": False,
    "strategy": "mobile",
    "final_url": None,
    "fetched_at": None,
    "skipped": False,
}


_FALLBACK_A11Y = {
    "score": 60,
    "summary": "Mock accessibility audit — set OPENAI_API_KEY and install [a11y] extra for real analysis.",
    "issues": [
        {
            "severity": "info",
            "title": "Mock response",
            "detail": "This accessibility review was generated by the offline mock provider.",
            "recommendation": (
                "Install the [a11y] extra (`pip install -e '.[a11y]'` then "
                "`playwright install chromium`) and set OPENAI_API_KEY to "
                "enable real WCAG 2.0/2.1 axe-core auditing."
            ),
        }
    ],
    "violations_count": 0,
    "tags_run": ["wcag2a", "wcag2aa", "wcag21a", "wcag21aa"],
    "viewport": "desktop",
    "final_url": None,
    "fetched_at": None,
    "skipped": False,
}


_FALLBACK_SECURITY = {
    "score": 70,
    "summary": "Mock security audit — set OPENAI_API_KEY for real header analysis.",
    "issues": [
        {
            "severity": "info",
            "title": "Mock response",
            "detail": "This security review was generated by the offline mock provider.",
            "recommendation": (
                "Set OPENAI_API_KEY to enable real HTTP security-header "
                "analysis via the security tool."
            ),
        }
    ],
    "checks_count": 0,
    "headers_seen": [],
    "headers_missing": [],
    "scheme": "https",
    "is_https": True,
    "server_banner": None,
    "cookie_flags": [],
    "final_url": None,
    "fetched_at": None,
    "skipped": False,
}


_FALLBACK_BRANDING = {
    "score": 65,
    "summary": "Mock branding audit — set OPENAI_API_KEY for real brand-identity analysis.",
    "issues": [
        {
            "severity": "info",
            "title": "Mock response",
            "detail": "This branding review was generated by the offline mock provider.",
            "recommendation": (
                "Set OPENAI_API_KEY to enable real brand-identity analysis "
                "(logo, favicon, OG image, theme color, social presence)."
            ),
        }
    ],
    "checks_count": 0,
    "logo_url": None,
    "favicons": [],
    "og_image": None,
    "twitter_image": None,
    "theme_color": None,
    "brand_colors": [],
    "social_links": [],
    "title_variants": {"page": None, "og": None, "twitter": None},
    "final_url": None,
    "fetched_at": None,
    "skipped": False,
}


_FALLBACK_QA = {
    "passed": True,
    "hallucinations_detected": False,
    "issues": []
}

_FALLBACK_CRO = {
    "score": 60,
    "summary": "Mock CRO audit.",
    "issues": [{"severity": "info", "title": "Mock CRO", "detail": "Mock.", "recommendation": "Mock"}],
}

_FALLBACK_UX = {
    "score": 60,
    "summary": "Mock UX audit.",
    "issues": [{"severity": "info", "title": "Mock UX", "detail": "Mock.", "recommendation": "Mock"}],
}

_FALLBACK_BUSINESS = {
    "score": 60,
    "summary": "Mock Business audit.",
    "issues": [{"severity": "info", "title": "Mock Business", "detail": "Mock.", "recommendation": "Mock"}],
}

_FALLBACK_BIZ_DOCS = {
    "executive_summary": "Mock Exec Summary.",
    "proposal": "Mock Proposal.",
    "roadmap": "Mock Roadmap.",
    "cold_email": "Mock Cold Email."
}


class MockProvider:
    """Returns predictable completions.

    Behavior:
    - ``!json:<payload>`` short-circuits and parses the payload as JSON.
    - When the request has ``response_format_json=True`` (used by ``LLMAgent``
      with a declared response_model) and no ``!json:`` directive, the mock
      returns a reasonable SEO-shaped fallback so pipelines run end-to-end
      without an API key.
    - Otherwise the response echoes the last user message with a prefix.
    """

    name = "mock"

    def __init__(self, default_prefix: str = "[mock] ") -> None:
        self._prefix = default_prefix
        self.calls: list[LLMRequest] = []

    async def complete(self, request: LLMRequest) -> LLMCompletion:
        self.calls.append(request)
        last_user = next(
            (m for m in reversed(request.messages) if m.role.value == "user"),
            None,
        )
        text = last_user.content if last_user else ""

        if text.startswith("!json:"):
            payload = text[len("!json:"):].strip()
            try:
                obj: Any = json.loads(payload or "{}")
            except json.JSONDecodeError:
                obj = {"raw": payload}
            content = json.dumps(obj)
        elif request.response_format_json:
            sys_text = next((m.content for m in request.messages if m.role.value == "system"), "")
            content = json.dumps(_fallback_for(sys_text, text))
        else:
            content = f"{self._prefix}{text}"

        return LLMCompletion(
            content=content,
            model=request.model,
            usage={
                "prompt_tokens": sum(len(m.content) for m in request.messages) // 4,
                "completion_tokens": len(content) // 4,
                "total_tokens": 0,
            },
            finish_reason="stop",
        )

    async def aclose(self) -> None:
        return None


def _kw(text: str, word: str) -> bool:
    """Whole-word keyword match (case-insensitive).

    Avoids false positives like ``aria`` matching inside ``variants``.
    """
    return re.search(rf"(?<![\w-]){re.escape(word)}(?![\w-])", text) is not None


def _kw_any(text: str, words: tuple[str, ...]) -> bool:
    """True if any of ``words`` matches as a whole word (case-insensitive)."""
    return any(_kw(text, w) for w in words)


def _fallback_for(sys_text: str, user_text: str) -> dict[str, Any]:
    """Pick a believable JSON shape based on prompt keywords.
    
    Covers the agents we ship today; later agents should set
    ``response_format_json=True`` and the mock will return the matching shape.
    """
    text = (sys_text + " " + user_text).lower()
    
    if _kw_any(text, ("qa", "qa_reviewer", "hallucinations")):
        return _FALLBACK_QA
    if _kw_any(text, ("business_writer", "proposal", "roadmap", "cold_email")):
        return _FALLBACK_BIZ_DOCS
    if _kw_any(text, ("cro", "cro_reviewer", "conversion")):
        return _FALLBACK_CRO
    if _kw_any(text, ("ux", "ux_reviewer", "user experience")):
        return _FALLBACK_UX
    if _kw_any(text, ("business", "business_reviewer", "value prop")):
        return _FALLBACK_BUSINESS
    
    if _kw_any(text, ("seo", "metadata", "headings")):
        return _FALLBACK_SEO
    if _kw_any(text, ("ui", "layout", "screenshot", "visual")):
        return _FALLBACK_UI
    if _kw_any(
        text,
        (
            "accessibility",
            "wcag",
            "axe",
            "aria",
            "contrast",
            "color contrast",
            "alt text",
            "screen reader",
        ),
    ):
        return _FALLBACK_A11Y
    if _kw_any(
        text,
        (
            "branding",
            "brand",
            "logo",
            "favicon",
            "theme color",
            "theme-color",
            "social link",
            "og:image",
            "twitter:image",
            "brand colors",
        ),
    ):
        return _FALLBACK_BRANDING
    if _kw_any(
        text,
        (
            "security",
            "csp",
            "hsts",
            "x-frame-options",
            "referrer-policy",
            "permissions-policy",
            "strict-transport-security",
            "mixed content",
            "secure; httponly",
        ),
    ):
        return _FALLBACK_SECURITY
    if _kw_any(
        text,
        (
            "performance",
            "pagespeed",
            "lighthouse",
            "core web vitals",
            "psi",
            "lcp",
            "cls",
        ),
    ):
        return _FALLBACK_PERF
    if _kw_any(text, ("plan", "steps")):
        return {
            "target_url": _extract_url(user_text) or "",
            "steps": [
                {"id": "crawl", "description": "Fetch.", "agent_role": "website_crawler"},
                {"id": "review", "description": "Review.", "agent_role": "seo_reviewer"},
                {"id": "report", "description": "Report.", "agent_role": "report_writer"},
            ],
            "notes": "Mock plan.",
        }
    return {"ok": True, "mock": True}


_URL_RX = re.compile(r"https?://\S+")


def _extract_url(text: str) -> str | None:
    m = _URL_RX.search(text)
    return m.group(0) if m else None


assert isinstance(MockProvider(), ILLMProvider)
