"""Deterministic LLM provider used in tests and offline runs."""

from __future__ import annotations

import json
import re
from typing import Any

from dhrubo.llm.interface import ILLMProvider, LLMCompletion, LLMRequest

_FALLBACK_SEO = {
    "score": 75,
    "summary": "Mock SEO audit — set OPENAI_API_KEY for real analysis.",
    "issues": [
        {
            "severity": "info",
            "title": "Mock response",
            "detail": "This audit was generated by the offline mock provider.",
            "recommendation": "Set OPENAI_API_KEY to enable real reviewer analysis.",
        }
    ],
}


class MockProvider:
    """Returns predictable completions.

    Behavior:
    - ``!json:<payload>`` short-circuits and parses the payload as JSON.
    - When the request has ``response_format_json=True`` (used by ``LLMAgent``
      with a declared response_model) and no ``!json:`` directive, the mock
      returns a reasonable SEO-shaped fallback so pipelines run end-to-end
      without an API key.
    - Otherwise the response echoes the last user message with a prefix.
    """

    name = "mock"

    def __init__(self, default_prefix: str = "[mock] ") -> None:
        self._prefix = default_prefix
        self.calls: list[LLMRequest] = []

    async def complete(self, request: LLMRequest) -> LLMCompletion:
        self.calls.append(request)
        last_user = next(
            (m for m in reversed(request.messages) if m.role.value == "user"),
            None,
        )
        text = last_user.content if last_user else ""

        if text.startswith("!json:"):
            payload = text[len("!json:"):].strip()
            try:
                obj: Any = json.loads(payload or "{}")
            except json.JSONDecodeError:
                obj = {"raw": payload}
            content = json.dumps(obj)
        elif request.response_format_json:
            content = json.dumps(_fallback_for(text))
        else:
            content = f"{self._prefix}{text}"

        return LLMCompletion(
            content=content,
            model=request.model,
            usage={
                "prompt_tokens": sum(len(m.content) for m in request.messages) // 4,
                "completion_tokens": len(content) // 4,
                "total_tokens": 0,
            },
            finish_reason="stop",
        )

    async def aclose(self) -> None:
        return None


def _fallback_for(user_text: str) -> dict[str, Any]:
    """Pick a believable JSON shape based on prompt keywords.

    Covers the agents we ship today; later agents should set
    ``response_format_json=True`` and the mock will return the matching shape.
    """
    text = user_text.lower()
    if "seo" in text or "metadata" in text or "headings" in text:
        return _FALLBACK_SEO
    if "plan" in text or "steps" in text:
        return {
            "target_url": _extract_url(user_text) or "",
            "steps": [
                {"id": "crawl", "description": "Fetch.", "agent_role": "website_crawler"},
                {"id": "review", "description": "Review.", "agent_role": "seo_reviewer"},
                {"id": "report", "description": "Report.", "agent_role": "report_writer"},
            ],
            "notes": "Mock plan.",
        }
    return {"ok": True, "mock": True}


_URL_RX = re.compile(r"https?://\S+")


def _extract_url(text: str) -> str | None:
    m = _URL_RX.search(text)
    return m.group(0) if m else None


assert isinstance(MockProvider(), ILLMProvider)
